server:
  port: 7779
  address: 0.0.0.0

  # 数据库相关配置
spring:
  datasource:
    url: jdbc:mysql://124.220.28.218:3306/ThreeLayers
    username: crz
    password: crz
    driver-class-name: com.mysql.cj.jdbc.Driver
